version: "3.7"

services:
    app:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend/api-site:/api-site
        command: >
            sh -c "python manage.py db_load && 
                   python manage.py makemigrations && 
                   python manage.py migrate && 
                   python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DOCKERIZED=TRUE
    
    react:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - './frontend:/app'
            - '/app/node_modules'
        command: >
            sh -c "npm start"
        depends_on: 
            - app
