# Generated by Django 3.2.4 on 2021-06-17 10:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_expire', models.BooleanField(default=False)),
                ('expiry_date', models.DateField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('cover_image', models.ImageField(null=True, upload_to=core.models.product_image_file_path)),
            ],
        ),
    ]
